domain: sophcon.github.io
title: Sophcon

collections:
  - services
  - news_articles
  - mission_statements

defaults:
  - scope:
      path: ""
      type: services
    values:
      layout: services
  - scope:
      path: ""
      type: news_articles
    values:
      layout: timeline_item
