domain: sophcon.github.io
title: Sophcon

paginate: 10 # pagination based on number of posts
paginate_path: "/blog/page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown

collections:
  services:
    output: false
  news_articles:
    output: false
  mission_statements:
    output: false
  sophcon_profiles:
    output: true
    permalink: "/company/about/:title/index.html"
  clients:
    output: true
    permalink: "/clients/:title/index.html"

defaults:
  - scope:
      path: ""
      type: services
    values:
      layout: services
  - scope:
      path: ""
      type: news_articles
    values:
      layout: timeline_item
  - scope:
      path: ""
      type: sophcon_profiles
    values:
      layout: profile
