domain: sophcon.github.io
title: Sophcon

collections:
  - services

defaults:
  - scope:
      path: ""
      type: services
    values:
      layout: services

navs:
  home:
    title: Home
    url: /
  services:
    title: Services
    url: /services/
  clients:
    title: clients
    url: /clients/
